CREATE TABLE IF NOT EXISTS documents (
  id INT PRIMARY KEY,
  title VARCHAR(255),
  description TEXT,
  file_url TEXT NOT NULL,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
